Trigger buttons with keyboard navigation
vizia/vizia pull request #187
Opened 2022-08-02 09:29 UTC by 0HyperCube

- `:focus-visible` and `focus-within` added
- Add focus styles to the default stylesheet
- TriggerDown and TriggerUp event which is called on left mouse down and on enter/space.
- Labels can describe other elements similar to the html for attribute

2022-08-02 20:03 UTC, geom3trik reviewed
Thank you again for work improving the keyboard navigation abilities of vizia. I've left some comments on the code but the main thing is that I'm skeptical of introducing these new `Trigger` events as opposed to using the mouse/keyboard events, but I think it's worth a disussion (either here or on discord). 

While messing around with these changes I noticed that there seems to be a bug on the button example where the button on the far right (the one with the checkmark) seems to get stuck in the active state when pressed/triggered.

2022-08-02 20:24 UTC, geom3trik commented
Okay so on reflection, after speaking with @rhelmot on Discord, they made the very good point that a uniform interface for accessibility and reducing the boilterplate for that is very important for usability. Therefore, I'm going to change my stance on the introduction of the `TriggerDown` and `TriggerUp` events and say that they are necessary. What would be good is if the mouse buttons and keys that constitute a trigger could be customized, perhaps through an `Environment` property, but I think this could be done at a later stage and not in this PR.

2022-08-04 09:41 UTC, 0HyperCube commented on core/resources/themes/default_theme.css
> +}
This doesn't actually happen because they both have the same selector specificity and the one at the bottom is applied last.

2022-08-04 09:44 UTC, 0HyperCube commented on core/src/window/window_event.rs
> +    },
The javascript `onclick` is also triggered on enter and space despite its name.

2022-08-04 09:46 UTC, geom3trik commented on core/resources/themes/default_theme.css
> +}
Yes but I think if you removed this rule would the `button:focus-visible` one not apply to accent buttons as well?

2022-08-04 09:46 UTC, geom3trik commented on core/src/window/window_event.rs
> +    },
Ah that's interesting. I think I much prefer your 'Trigger' naming for this.

2022-08-04 09:53 UTC, 0HyperCube commented on core/resources/themes/default_theme.css
> +}
It doesn't appear to?

2022-08-04 10:01 UTC, geom3trik commented on core/resources/themes/default_theme.css
> +}
Hmm okay. Could be a bug, or I might just be wrong. We can leave it as it is here then and I'll look into that separately.

2022-08-04 10:23 UTC, 0HyperCube commented on core/resources/themes/default_theme.css
> +}
Putting the `button:focus-visible` rule further down the stylesheet allows this block to be removed.

2022-08-04 10:30 UTC, 0HyperCube commented on core/src/views/label.rs
> +    describing: Option<Entity>,
We already have a mapping from id string to entity id for the style system.

2022-08-04 10:37 UTC, geom3trik commented on core/resources/themes/default_theme.css
> +}
Sounds like maybe a bug with the specificity. I'll take a look but probably the new style system currently in development will fix this.

2022-08-04 10:39 UTC, geom3trik commented on core/src/views/label.rs
> +    describing: Option<Entity>,
We do? I can't seem to find it, could you link the line? I see the mapping from entity to id string but not the other way around.

2022-08-04 17:31 UTC, 0HyperCube commented on core/src/views/label.rs
> +    describing: Option<Entity>,
Actually I misread it.

2022-08-05 22:06 UTC, geom3trik commented
Is this ready for review again or are you still working on it?

2022-08-06 07:54 UTC, 0HyperCube commented
Ready for review - for the entity id changing on binding I added a hashmap in context for mapping EntityIdentifiers to Entities:
```rs
let el_identifier = cx.new_entity_identifier();
Binding::new(cx, Environment::locale, move |cx, locale| {
    Element::new(cx).identify(el_identifier);
});
```

2022-08-07 21:11 UTC, geom3trik commented
So we already have a way to add an id to an entity with the `id()` modifier <https://docs.vizia.dev/vizia/handle/struct.Handle.html#method.id>. This is currently used for css selector matching but is there any reason we can't use this for referring to views? What I meant before was that we have a mapping from entity to id, and all we need is another mapping from id to entity.

2022-08-10 08:01 UTC, 0HyperCube commented
I wanted to see if I could avoid using unscoped strings which had led me to difficulty refactoring and strange bugs with typos or id conflicts in html. However I have now switched to using the strings.

2022-08-10 08:53 UTC, geom3trik commented
> I wanted to see if I could avoid using unscoped strings which had led me to difficulty refactoring and strange bugs with typos or id conflicts in html.

Hmm okay, you make a very good point. I think consistency with html/css is a nice to have here because it's reduces the learning curve, so I'm going to say let's stick with the strings. However this may be something we could come back to or adapt to reduce pitfalls at some point.

2022-08-10 08:53 UTC, geom3trik commented
> I wanted to see if I could avoid using unscoped strings which had led me to difficulty refactoring and strange bugs with typos or id conflicts in html.

Hmm okay, you make a very good point. I think consistency with html/css is a nice to have here because it's reduces the learning curve, so I'm going to say let's stick with the strings. However this may be something we could come back to or adapt to reduce pitfalls at some point.

2022-08-10 11:53 UTC, geom3trik requested changes
This all looks good to me. One thing missing though is removal of the ID and entity from the `entity_identifier` when an entity is removed. Once we've got that then this looks good to merge to me.

2022-08-10 14:12 UTC, 0HyperCube commented
Good spot, I've added cleaning up of the entity identifiers now.

2022-08-10 17:54 UTC, geom3trik approved these changes

2022-08-10 17:56 UTC, merged